version: '3.9'

services:
  postgres_app:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    networks:
      - app-network

  django_app:
    build: 
      context: ./django_app
      dockerfile: Dockerfile.dev
    command: sh -c "
          python manage.py collectstatic --noinput
          && python manage.py makemigrations --noinput
          && python manage.py migrate --noinput
          && python manage.py runserver 0.0.0.0:8000
          || true
        "
    volumes:
      - ./django_app/:/home/django_app
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      - postgres_app
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge