# pull official base image
FROM python:3.11-alpine

# set work directory
WORKDIR /home/django_app

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt .
RUN pip install -r requirements.txt

# copy entrypoint.dev.sh
COPY ./entrypoint.dev.sh /usr/local/bin/
RUN sed -i 's/\r$//g' /usr/local/bin/entrypoint.dev.sh
RUN chmod +x /usr/local/bin/entrypoint.dev.sh

# copy project
COPY . .

ENTRYPOINT ["/usr/local/bin/entrypoint.dev.sh"]