upstream dajngo4_vue_template_django_template_django {
    server unix:///var/www/python/dajngo4_vue_template/dajngo4_vue_template/config/uwsgi/dajngo4_vue_template.sock;
}

server {
    listen 80;
    server_name     dajngo4_vue_template.com;

    charset     utf-8;
    client_max_body_size 75M;

    location / {
        uwsgi_pass  dajngo4_vue_template_django_template_django;
        include     /var/www/python/dajngo4_vue_template/dajngo4_vue_template/config/uwsgi/uwsgi_params;
    }
    location /media  {
        alias /var/www/python/dajngo4_vue_template/media;
    }
    location /static {
        alias /var/www/python/dajngo4_vue_template/staticfiles;
    }
    location /robots.txt {
        alias /var/www/python/dajngo4_vue_template/web/robots.txt;
    }
    location /sitemap.xml {
        alias /var/www/python/dajngo4_vue_template/web/sitemap.xml;
    }
}
